2021-07-22 10:54:51.253 [error] emulator Error in process <0.269.0> with exit value:
{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => <0.269.0>},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.Processor',kill_process,1,[{file,"lib/processor.ex"},{line,16}]}]}
2021-07-22 11:10:59.854 [error] <0.271.0>@Elixir.Supervisor:start_link CRASH REPORT Process <0.271.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Supervisor':start_link([{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]) in application_master:init/4 line 142
2021-07-22 11:11:28.131 [error] <0.265.0>@Elixir.Supervisor:start_link CRASH REPORT Process <0.265.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Supervisor':start_link([{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]) in application_master:init/4 line 142
2021-07-22 11:11:52.666 [error] <0.265.0>@Elixir.Supervisor:start_link CRASH REPORT Process <0.265.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Supervisor':start_link([{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]) in application_master:init/4 line 142
2021-07-22 12:05:05.346 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason <0.280.0> in context start_error
2021-07-22 12:05:05.346 [error] <0.277.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:05:15.378 [error] <0.253.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason <0.254.0> in context start_error
2021-07-22 12:05:15.378 [error] <0.251.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.251.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:05:29.454 [error] <0.253.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason <0.254.0> in context start_error
2021-07-22 12:05:29.455 [error] <0.251.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.251.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:05:42.349 [error] <0.268.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason ok in context start_error
2021-07-22 12:05:42.349 [error] <0.266.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:06:19.249 [error] <0.268.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason ok in context start_error
2021-07-22 12:06:19.249 [error] <0.266.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:07:59.402 [error] <0.282.0>@Elixir.IO:pust CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.IO':pust(<<"children = [{Processor, \"github\"}, {Processor, \"trello\"}]">>) in application_master:init/4 line 142
2021-07-22 12:08:27.259 [error] <0.276.0>@Elixir.IO:pust CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.IO':pust(<<"children = [{Processor, \"github\"}, {Processor, \"trello\"}]">>) in application_master:init/4 line 142
2021-07-22 12:22:08.566 [error] <0.276.0>@Elixir.IO:pust CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.IO':pust(<<"children = [{Processor, \"github\"}, {Processor, \"trello\"}]">>) in application_master:init/4 line 142
2021-07-22 12:36:09.838 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child github started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason <0.280.0> in context start_error
2021-07-22 12:36:09.838 [error] <0.277.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:36:37.501 [error] <0.277.0>@Elixir.Processor.Application:start CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Processor.Application':start(normal, []) in application_master:init/4 line 142
2021-07-22 12:40:29.115 [error] <0.279.0>@supervisor:init:330 CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({'Elixir.Processor',<<"trello">>}, init, [[{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]]) in supervisor:init/1 line 330
2021-07-22 12:40:29.115 [error] <0.278.0>@supervisor:init:330 CRASH REPORT Process <0.278.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({'Elixir.Processor',<<"github">>}, init, [[{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]]) in supervisor:init/1 line 330
2021-07-22 12:40:29.115 [error] <0.276.0>@supervisor:init:330 CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: bad argument in call to erlang:apply({'Elixir.Processor',<<"github">>}, init, [[{strategy,one_for_one},{name,'Elixir.Processor.Supervisor'}]]) in supervisor:init/1 line 330 in application_master:init/4 line 142
2021-07-22 14:35:02.852 [error] <0.271.0> CRASH REPORT Process <0.271.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Processor was given as a child to a supervisor\nbut it does not implement child_spec/1.\n\nIf you own the given module, please define a child_spec/1 function\nthat receives an argument and returns a child specification as a map.\nFor example:\n\n    def child_spec(opts) do\n      %{\n        id: __MODULE__,\n        start: {__MODULE__, :start_link, [opts]},\n        type: :worker,\n        restart: :permanent,\n     ...">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-22 14:35:18.023 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: {start_spec,{duplicate_child_name,'Elixir.Processor'}} in gen_server:init_it/6 line 407
2021-07-22 14:35:18.023 [error] <0.266.0> CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: {{start_spec,{duplicate_child_name,'Elixir.Processor'}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:35:41.737 [error] <0.268.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.269.0>} in context start_error
2021-07-22 14:35:41.737 [error] <0.266.0> CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.269.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:36:16.904 [error] <0.268.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.269.0>} in context start_error
2021-07-22 14:36:16.905 [error] <0.266.0> CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.269.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:37:02.511 [error] <0.267.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.268.0>} in context start_error
2021-07-22 14:37:02.511 [error] <0.265.0> CRASH REPORT Process <0.265.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.268.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:37:23.612 [error] <0.253.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.254.0>} in context start_error
2021-07-22 14:37:23.613 [error] <0.251.0> CRASH REPORT Process <0.251.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.254.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:37:33.407 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.265.0>} in context start_error
2021-07-22 14:37:33.407 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.265.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:39:40.610 [error] <0.276.0>@Elixir.Processor:child_spec:36 CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: bad argument in call to erlang:binary_to_atom([<<"github">>], utf8) in 'Elixir.Processor':child_spec/1 line 36 in application_master:init/4 line 142
2021-07-22 14:40:12.006 [error] <0.279.0>@Elixir.Processor:start_connection:50 Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link([<<"github">>]) at undefined exit with reason bad argument in call to erlang:byte_size([<<"github">>]) in 'Elixir.Processor':start_connection/1 line 50 in context start_error
2021-07-22 14:40:12.006 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Processor',{badarg,[{erlang,byte_size,[[<<"github">>]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Processor',start_connection,1,[{file,"lib/processor.ex"},{line,50}]},{'Elixir.Processor',init,1,[{file,"lib/processor.ex"},{line,18}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Processor.Application',...}} in application_master:init/4 line 142
2021-07-22 14:41:26.584 [error] <0.279.0>@Elixir.Processor:start_connection:50 CRASH REPORT Process <0.279.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(["github"]) in 'Elixir.Processor':start_connection/1 line 50
2021-07-22 14:41:26.584 [error] <0.278.0>@Elixir.Processor:start_connection:50 Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(["github"]) at undefined exit with reason bad argument in call to erlang:byte_size(["github"]) in 'Elixir.Processor':start_connection/1 line 50 in context start_error
2021-07-22 14:41:26.584 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Processor',{badarg,[{erlang,byte_size,[["github"]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.Processor',start_connection,1,[{file,"lib/processor.ex"},{line,50}]},{'Elixir.Processor',init,1,[{file,"lib/processor.ex"},{line,18}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.Processor.Application',...}} in application_master:init/4 line 142
2021-07-22 14:44:21.797 [error] <0.280.0> gen_server 'Elixir.Processor' terminated with reason: bad return value: ok
2021-07-22 14:44:21.802 [error] <0.280.0>@gen_server:handle_common_reply:815 CRASH REPORT Process 'Elixir.Processor' with 0 neighbours exited with reason: bad return value: ok in gen_server:handle_common_reply/8 line 815
2021-07-22 14:44:21.802 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(<<"github">>) at <0.280.0> exit with reason bad return value: ok in context child_terminated
2021-07-22 14:44:21.808 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(<<"github">>) at <0.280.0> exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.311.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.298.0>},60000]}} in context start_error
2021-07-22 14:44:21.808 [error] <0.298.0> CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.311.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.298.0>},60000]}} in gen_server:call/3 line 247
2021-07-22 14:44:21.811 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(<<"github">>) at {restarting,<0.280.0>} exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.325.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.313.0>},60000]}} in context start_error
2021-07-22 14:44:21.811 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.325.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.313.0>},60000]}} in gen_server:call/3 line 247
2021-07-22 14:44:21.815 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(<<"github">>) at {restarting,<0.280.0>} exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.339.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.327.0>},60000]}} in context start_error
2021-07-22 14:44:21.815 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Processor' started with 'Elixir.Processor':start_link(<<"github">>) at {restarting,<0.280.0>} exit with reason reached_max_restart_intensity in context shutdown
2021-07-22 14:47:16.563 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: {start_spec,{duplicate_child_name,'Elixir.Processor'}} in gen_server:init_it/6 line 407
2021-07-22 14:47:16.563 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{start_spec,{duplicate_child_name,'Elixir.Processor'}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:47:33.250 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 14:47:33.251 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:50:32.614 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 14:50:32.615 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 14:51:24.704 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child trello started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 14:51:24.705 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,trello,{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:00:29.216 [error] <0.278.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.279.0>} in context start_error
2021-07-22 15:00:29.216 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{already_started,<0.279.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:05:20.250 [error] <0.278.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.279.0>} in context start_error
2021-07-22 15:05:20.250 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{already_started,<0.279.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:08:23.637 [error] <0.284.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :name option to be one of the following:\n\n  * nil\n  * atom\n  * {:global, term}\n  * {:via, module, term}\n\nGot: \"github\"\n">>},[{'Elixir.GenServer',do_start,4,[{file,"lib/gen_server.ex"},{line,944}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},...]},...]}} in context start_error
2021-07-22 15:08:23.637 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :name option to be one of the following:\n\n  * nil\n  * atom\n  * {:global, term}\n  * {:via, module, term}\n\nGot: \"github\"\n">>},[{'Elixir.GenServer',do_start,4,[{file,"lib/gen_server.ex"},{line,944}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',...},...]}}}},...} in application_master:init/4 line 142
2021-07-22 15:09:12.832 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.309.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.297.0>},60000]}} in context start_error
2021-07-22 15:09:12.833 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.309.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.297.0>},60000]}}}},{'Elixir.Processor.Application',start,[normal,...]}} in application_master:init/4 line 142
2021-07-22 15:13:24.853 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 15:13:24.853 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:14:05.244 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason <0.280.0> in context start_error
2021-07-22 15:14:05.244 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',<0.280.0>}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:14:24.284 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 15:14:24.285 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:15:17.945 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :name option to be one of the following:\n\n  * nil\n  * atom\n  * {:global, term}\n  * {:via, module, term}\n\nGot: \"github\"\n">>},[{'Elixir.GenServer',do_start,4,[{file,"lib/gen_server.ex"},{line,944}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},...]},...]}} in context start_error
2021-07-22 15:15:17.946 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"expected :name option to be one of the following:\n\n  * nil\n  * atom\n  * {:global, term}\n  * {:via, module, term}\n\nGot: \"github\"\n">>},[{'Elixir.GenServer',do_start,4,[{file,"lib/gen_server.ex"},{line,944}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',...},...]}}}},...} in application_master:init/4 line 142
2021-07-22 15:15:30.236 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.309.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.297.0>},60000]}} in context start_error
2021-07-22 15:15:30.236 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.309.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.297.0>},60000]}}}},{'Elixir.Processor.Application',start,[normal,...]}} in application_master:init/4 line 142
2021-07-22 15:17:21.060 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at undefined exit with reason {already_started,<0.280.0>} in context start_error
2021-07-22 15:17:21.060 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Trello',{already_started,<0.280.0>}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:17:34.905 [error] <0.279.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.294.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.280.0>},60000]}} in context start_error
2021-07-22 15:17:34.905 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.294.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.280.0>},60000]}}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:17:45.231 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.279.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.265.0>},60000]}} in context start_error
2021-07-22 15:17:45.231 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.279.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.265.0>},60000]}}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:18:08.182 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at undefined exit with reason {{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.279.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.265.0>},60000]}} in context start_error
2021-07-22 15:18:08.182 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Git',{{shutdown,{server_initiated_close,405,<<"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'raw_input' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.">>}},{gen_server,call,[<0.279.0>,{call,{'queue.declare',0,<<"raw_input">>,false,false,true,false,false,[]},none,<0.265.0>},60000]}}}},{'Elixir.Processor.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-07-22 15:23:10.330 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at <0.265.0> exit with reason killed in context child_terminated
2021-07-22 15:23:22.494 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at <0.335.0> exit with reason killed in context child_terminated
2021-07-22 15:23:34.947 [error] <0.264.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at <0.282.0> exit with reason killed in context child_terminated
2021-07-22 15:23:42.272 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 236
2021-07-22 15:33:54.113 [error] <0.253.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Trello' started with 'Elixir.Processor':start_link(<<"trello">>) at <0.271.0> exit with reason killed in context child_terminated
2021-07-22 15:33:54.119 [error] <0.253.0> Supervisor 'Elixir.Processor.Supervisor' had child 'Elixir.Git' started with 'Elixir.Processor':start_link(<<"github">>) at <0.254.0> exit with reason killed in context child_terminated
