2021-07-21 11:53:36.306 [error] <0.270.0>@Elixir.Connector:start_connection CRASH REPORT Process <0.270.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Connector':start_connection()
2021-07-21 11:53:36.314 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :error was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:05:02.264 [error] <0.297.0>@Elixir.Connector.Connector:init:13 CRASH REPORT Process <0.297.0> with 0 neighbours crashed with reason: bad argument in call to erlang:spawn('Elixir.Connector.Extractor', loop, nil) in 'Elixir.Connector.Connector':init/1 line 13
2021-07-21 12:05:02.268 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :error was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:05:16.519 [error] <0.286.0>@Elixir.Connector.Connector:init:13 CRASH REPORT Process <0.286.0> with 0 neighbours crashed with reason: bad argument in call to erlang:spawn('Elixir.Connector.Extractor', loop, nil) in 'Elixir.Connector.Connector':init/1 line 13
2021-07-21 12:05:16.527 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :error was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:07:13.821 [error] emulator Error in process <0.292.0> with exit value:
{{badarity,{#Fun<Elixir.Connector.Connector.0.11176859>,[]}},[{erlang,apply,2,[]}]}
2021-07-21 12:07:13.866 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:07:55.252 [error] emulator Error in process <0.328.0> with exit value:
{{badarity,{#Fun<Elixir.Connector.Connector.0.11176859>,[]}},[{erlang,apply,2,[]}]}
2021-07-21 12:07:55.295 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:09:49.722 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:09:49.722 [error] emulator Error in process <0.287.0> with exit value:
{function_clause,[{'Elixir.String',trim,[{error,terminated}],[{file,"lib/string.ex"},{line,1231}]},{'Elixir.Connector.Extractor',loop,0,[{file,"lib/connector/extractor.ex"},{line,5}]}]}
2021-07-21 12:11:42.006 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:11:42.006 [error] emulator Error in process <0.282.0> with exit value:
{function_clause,[{'Elixir.String',trim,[{error,terminated}],[{file,"lib/string.ex"},{line,1231}]},{'Elixir.Connector.Extractor',loop,0,[{file,"lib/connector/extractor.ex"},{line,5}]}]}
2021-07-21 12:14:45.534 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:14:49.330 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:16:36.465 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:17:12.575 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:17:43.736 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:17:43.736 [error] <0.291.0> gen_server 'Elixir.Connector.Connector' terminated with reason: {terminated,[{io,put_chars,[standard_io,unicode,[<<" [x] Sent '[connectors.github.new] fst msg'">>,10]],[]},{'Elixir.Connector.Connector',handle_call,3,[{file,"lib/connector/connector.ex"},{line,21}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2021-07-21 12:17:43.743 [error] <0.291.0> CRASH REPORT Process 'Elixir.Connector.Connector' with 0 neighbours crashed with reason: {terminated,[{io,put_chars,[standard_io,unicode,[<<" [x] Sent '[connectors.github.new] fst msg'">>,10]],[]},{'Elixir.Connector.Connector',handle_call,3,[{file,"lib/connector/connector.ex"},{line,21}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2021-07-21 12:18:53.597 [error] emulator Error in process <0.287.0> with exit value:
{undef,[{thread,sleep,[200000000000],[]},{'Elixir.Connector.Extractor',loop,0,[{file,"lib/connector/extractor.ex"},{line,9}]}]}
2021-07-21 12:18:53.598 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:19:40.292 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:20:03.640 [error] emulator Error in process <0.287.0> with exit value:
{timeout_value,[{timer,sleep,1,[{file,"timer.erl"},{line,152}]},{'Elixir.Connector.Extractor',loop,0,[{file,"lib/connector/extractor.ex"},{line,9}]}]}
2021-07-21 12:20:03.643 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:20:29.047 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:22:02.718 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:22:17.731 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:23:29.768 [error] <0.282.0>@Elixir.Connector:start_link CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Connector':start_link() in application_master:init/4 line 142
2021-07-21 12:24:03.311 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:24:37.881 [error] <0.284.0> Supervisor 'Elixir.Connector.Supervisor' had child 'Elixir.Connector' started with 'Elixir.Connector':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.Connector',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_..."},...]}]}} in context start_error
2021-07-21 12:24:37.881 [error] <0.282.0>@Elixir.Connector.Application:start:22 CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,'Elixir.Connector',{'EXIT',{undef,[{'Elixir.Connector',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_s..."},...]},...]}}}}} in 'Elixir.Connector.Application':start/2 line 22 in application_master:init/4 line 142
2021-07-21 12:25:06.394 [error] <0.284.0> Supervisor 'Elixir.Connector.Supervisor' had child 'Elixir.Connector' started with 'Elixir.Connector':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.Connector',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_..."},...]}]}} in context start_error
2021-07-21 12:25:06.394 [error] <0.282.0>@Elixir.Connector.Application:start:22 CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,'Elixir.Connector',{'EXIT',{undef,[{'Elixir.Connector',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_s..."},...]},...]}}}}} in 'Elixir.Connector.Application':start/2 line 22 in application_master:init/4 line 142
2021-07-21 12:25:23.161 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:26:06.575 [error] <0.282.0>@Elixir.Connector.Application:start CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: bad return value #{active => 0,specs => 0,supervisors => 0,workers => 0} from 'Elixir.Connector.Application':start(normal, []) in application_master:init/4 line 142
2021-07-21 12:27:05.700 [error] <0.284.0> Supervisor 'Elixir.Connector.Supervisor' had child 'Elixir.Connector.Connector' started with 'Elixir.Connector.Connector':start_link(nil) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Connector.Connector',start_link,[nil],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,...}]}} in context start_error
2021-07-21 12:27:05.700 [error] <0.282.0>@Elixir.Connector.Application:start:20 CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,'Elixir.Connector.Connector',{'EXIT',{undef,[{'Elixir.Connector.Connector',start_link,[nil],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,...},...]}}}}} in 'Elixir.Connector.Application':start/2 line 20 in application_master:init/4 line 142
2021-07-21 12:27:21.744 [error] <0.284.0> Supervisor 'Elixir.Connector.Supervisor' had child 'Elixir.Connector.Connector' started with 'Elixir.Connector.Connector':start_link(nil) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Connector.Connector',start_link,[nil],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,...}]}} in context start_error
2021-07-21 12:27:21.744 [error] <0.282.0>@Elixir.Connector.Application:start:20 CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,'Elixir.Connector.Connector',{'EXIT',{undef,[{'Elixir.Connector.Connector',start_link,[nil],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1234}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,...},...]}}}}} in 'Elixir.Connector.Application':start/2 line 20 in application_master:init/4 line 142
2021-07-21 12:27:58.456 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module :ok was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 631 in application_master:init/4 line 142
2021-07-21 12:36:32.406 [error] emulator Error in process <0.299.0> with exit value:
{undef,[{'Elixir.Connector.Extractor',loop,[],[]}]}
2021-07-21 12:40:37.228 [error] <0.282.0>@Elixir.Connector.Application:start CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: bad return value #{active => 1,specs => 1,supervisors => 0,workers => 1} from 'Elixir.Connector.Application':start(normal, []) in application_master:init/4 line 142
2021-07-21 12:40:37.228 [error] emulator Error in process <0.286.0> with exit value:
{function_clause,[{'Elixir.String',trim,[{error,terminated}],[{file,"lib/string.ex"},{line,1231}]},{'Elixir.Connector.Extractor',loop,1,[{file,"lib/connector/extractor.ex"},{line,5}]}]}
2021-07-21 14:03:09.935 [error] <0.306.0>@Elixir.Connector.Application:start CRASH REPORT Process <0.306.0> with 0 neighbours exited with reason: bad return value #{active => 1,specs => 1,supervisors => 0,workers => 1} from 'Elixir.Connector.Application':start(normal, []) in application_master:init/4 line 142
2021-07-21 14:03:09.935 [error] emulator Error in process <0.310.0> with exit value:
{function_clause,[{'Elixir.String',trim,[{error,terminated}],[{file,"lib/string.ex"},{line,1231}]},{'Elixir.Connector.Extractor',loop,1,[{file,"lib/connector/extractor.ex"},{line,5}]}]}
2021-07-21 14:06:51.309 [error] emulator Error in process <0.272.0> with exit value:
{{badmatch,[<<"asd ds">>]},[{'Elixir.Connector.Extractor',loop,1,[{file,"lib/connector/extractor.ex"},{line,3}]}]}
